name: grizzly_primitives
description: Primitives (Index, Pair, Extent) for Grizzly
version: 3.0.0
homepage: https://github.com/grizzly-dart/grizzly_primitives

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  quiver_hashcode: ^2.0.0
  grizzly_range: ^3.0.0

dev_dependencies:
  test:
  pedantic: