name: grizzly_primitives
description: Primitives (Index, Pair, Extent) for Grizzly
version: 3.0.0
homepage: https://github.com/grizzly-dart/grizzly_primitives
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  grizzly_range: ^2.0.4

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.11.0
