name: grizzly_primitives
description: Primitives (Index, Pair, Extent) for Grizzly
version: 2.0.1
homepage: https://github.com/grizzly-dart/grizzly_primitives
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: